# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0013_auto_20170327_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivetest',
            name='archive_type',
        ),
        migrations.DeleteModel(
            name='ArchiveType',
        ),
    ]
