# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import hacktester.tester.models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0014_auto_20170327_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=hacktester.tester.models.tests_upload_path),
        ),
        migrations.AddField(
            model_name='test',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
