# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0016_migrate_plainunittest_to_test_objects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivetest',
            name='test_ptr',
        ),
        migrations.RemoveField(
            model_name='binaryunittest',
            name='test_ptr',
        ),
        migrations.RemoveField(
            model_name='plainunittest',
            name='test_ptr',
        ),
        migrations.DeleteModel(
            name='ArchiveTest',
        ),
        migrations.DeleteModel(
            name='BinaryUnittest',
        ),
        migrations.DeleteModel(
            name='PlainUnittest',
        ),
    ]
