# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 10:22
from __future__ import unicode_literals

import uuid

from django.db import migrations, transaction
from django.core.files.base import ContentFile


class Migration(migrations.Migration):

    def migrate_testwithplaintext_to_solution_objects(apps, schema_editor):
        TestWithPlainText = apps.get_model('tester', 'TestWithPlainText')
        Solution = apps.get_model('tester', 'Solution')

        with transaction.atomic():
            for testwithbinaryfile in TestWithPlainText.objects.all():
                solution_file = ContentFile(content=testwithbinaryfile.solution_code, name=str(uuid.uuid4()))

                solution = Solution()
                solution.file = solution_file
                solution.save()

    dependencies = [
        ('tester', '0018_auto_20170327_1019'),
    ]

    operations = [
        migrations.RunPython(migrate_testwithplaintext_to_solution_objects)
    ]
