# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0019_migrate_testwithplaintext_to_solution_objects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testwithbinaryfile',
            name='testrun_ptr',
        ),
        migrations.RemoveField(
            model_name='testwithplaintext',
            name='testrun_ptr',
        ),
        migrations.DeleteModel(
            name='TestWithBinaryFile',
        ),
        migrations.DeleteModel(
            name='TestWithPlainText',
        ),
    ]
