# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0020_auto_20170327_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testrun',
            old_name='solutions',
            new_name='solution',
        ),
        migrations.RenameField(
            model_name='testrun',
            old_name='tests',
            new_name='test',
        ),
    ]
