# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-07 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0021_auto_20170327_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='container_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
